### ISSUE TITLE
Cart Quantity + Persist State

### ISSUE THREAD

**Issue by rylanharper** [jsappme/gridsome-shopify-starter#3]
Hi there! Thank you for this repo!😄 This is my first time trying out Gridsome with Shopify and I was wondering if its possible to persist the cart state across page-refresh/reloads... Possibly with vue-persist or cookies. 

Also I was wondering if you had any suggestions for best practices on adding in a cart quantity input.. Would that be created in the vuex store? I know when using Nuxt it is something like this:

```
updateCartQty({ state, commit }, data) {
    const cartItem = state.items.find(item => item.id === data.item.id)

    const payload = {
      cartItem: cartItem,
      qty: data.qty
    }
    commit('updateCartQty', payload)
  },
```
I am not sure how to add that in with Gridsome. Any suggestions? If this repo had these two things it would be perfect😁

**Comment by jsappme** [comment]
Thank you for your comment. 

Yes I would use https://github.com/championswimmer/vuex-persist to save the cart content for later visits.

For the cart qty, you will need to add a function to change the quantities in the this.$store.state.cart

Feel free to contact me at herve76@gmail.com if you need more advanced help or custom Gridsome Shopify development.
